---
roles:
  - name: geerlingguy.swap
  - name: geerlingguy.containerd
  - name: geerlingguy.kubernetes
  - name: geerlingguy.glusterfs
  - name: geerlingguy.helm

collections:
  - name: kubernetes.core
    version: 2.2.3
    source: https://galaxy.ansible.com
  - name: ansible.posix
    version: 1.3.0
  - name: community.crypto