apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: glusterfs-system
subsets:
{% for item in groups['gluster'] %}
- addresses:
  - ip: {{ hostvars[item].ansible_host }}
  ports:
  - port: 1729
{% endfor %}