---
service:
  type: LoadBalancer
updateStrategy:
  type: RollingUpdate # Recreate sur pv rwOnce ou RollingUpdate
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
#admin:
#  user: "admin"
#  password: "D8cu6XlCct"
persistence:
  storageClass: "{{ DefaultStorageClassName }}"
# existingClaim: "{{ DefaultPersistanceVolume }}"
# size: 5Gi