---
roles:
  - name: geerlingguy.swap
  - name: geerlingguy.containerd
  - name: geerlingguy.kubernetes
  - name: geerlingguy.glusterfs
  - name: geerlingguy.helm

collections:
  - name: community.kubernetes