---
- hosts: node0
  become: yes

  vars_files:
    - vars/main.yml

  tasks:

    # Afin d'utiliser le module kubernetes.core, il faut le module pip kubernetes sur la cible pour qu'il puisse s'exécuter (et pip).
    - name: "[Ansible module kubernetes] Ensure PIP3 is installed."
      apt:
        name:
          - python3-pip
        state: present
    - name: "[Ansible module kubernetes] Install kubernetes python package on version 21.7.0"
      pip:
        name: kubernetes
    # Installation du plugins helm diff pour faciliter les upgrades
    - name: "[Ansible module kubernetes] Install Helm diff plugin"
      kubernetes.core.helm_plugin:
        plugin_path: https://github.com/databus23/helm-diff
        state: present
######################################################

    - name: Minio search admin user
      ansible.builtin.command: 
        cmd: bash -c "kubectl get secret --namespace persisting minio -o jsonpath='{.data.root-user}' | base64 --decode"
      register: minioUser
    - name: Minio search admin password
      ansible.builtin.command:
        cmd: bash -c "kubectl get secret --namespace persisting minio -o jsonpath='{.data.root-password}' | base64 --decode"
      register: minioPassword
    - name: Prints minio-user and minio-password
      ansible.builtin.debug:
        msg: "Minio Admin  {{ minioUser.stdout }} / {{ minioPassword.stdout }}"