apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
subsets:
- addresses:
  - ip: 192.168.56.140
  ports:
  - port: 1
- addresses:
  - ip: 192.168.56.141
  ports:
  - port: 1
- addresses:
  - ip: 192.168.56.142
  ports:
  - port: 1
- addresses:
  - ip: 192.168.56.143
  ports:
  - port: 1
