---
all:
  vars:
    ansible_become: 'true'
    ansible_connection: lxd
    ansible_user: root
    # simple lxd.yml including virtual machines and containers
    plugin: community.general.lxd
    url: unix:/var/snap/lxd/common/lxd/unix.socket
    type_filter: both
    state: RUNNING
  children:
    gluster:
      hosts:
        node0: {}
        node1: {}
    k8s:
      children:
        k8smaster:
          hosts:
            node0: {}
        k8snodes:
          hosts:
            node0: {}
            node1: {}
