---
- hosts: k8s
  become: yes

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Copy Flannel manifest tailored for Vagrant.
      copy:
        src: files/manifests/kube-system/kube-flannel-vagrant.yml
        dest: "~/kube-flannel-vagrant.yml"
    - name: Ensure br_netfilter is enabled.
      modprobe:
        name: br_netfilter
        state: present
    - name: "net.ipv4.ip_forward=1"
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
    - name: "vm.swappiness=0 pas d'utilisation de disque"
      ansible.posix.sysctl:
        name: vm.swappiness
        value: '0'
        state: present        

  roles:
    - role: geerlingguy.swap
      tags: ['swap', 'kubernetes']

    - role: geerlingguy.containerd
      tags: ['containerd']

    - role: geerlingguy.kubernetes
      tags: ['kubernetes']